train:
  # Name used to identify the run. Data inside `job_dir` will be stored under
  # `run_name`.
  run_name: forms-ocr
  # Base directory in which model checkpoints & summaries (for Tensorboard) will
  # be saved.
  job_dir: jobs/
  save_checkpoint_secs: 10
  save_summaries_secs: 10

  # Number of epochs (complete dataset batches) to run.
  num_epochs: 15

dataset:
  type: object_detection
  # From which directory to read the dataset.
  dir: datasets
  # image_preprocessing:
  #   min_size: 600
  #   max_size: 1024
  # data_augmentation:
  #   - flip:
  #       left_right: False
  #       up_down: False
  #       prob: 0.5

model:
  type: fasterrcnn
  network:
    # Total number of classes to predict.
    num_classes: 2
